# stage → 단계

stages:
  - dockerbuild-push

package:
  image: docker:latest
  stage: dockerbuild-push
  services:
    - docker:dind
  before_script:
    - docker login registry.gitlab.com -u $GITLAB_USER -p $GITLAB_PASSWORD
  script:
    - docker build -t registry.gitlab.com/$GITLAB_USER/gitlab-docker-cicd-practice .
    - docker push registry.gitlab.com/$GITLAB_USER/gitlab-docker-cicd-practice
  after_script:
    - docker logout